server:
  port: 8022

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/config?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MYSQL  #指定数据库类型
    show-sql: true   #控制台打印SQL
    hibernate:
      ddl-auto: update #建表策略 根据实体更新表结构
      naming:   #表字段命名策略
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 此配置不会将驼峰转为下划线
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

fdfs:
  so-timeout: 100000
  connect-timeout: 60000
  tracker-list:
    - 192.168.1.151:22122
  prefix:
    strip: true
